// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {config} from '../models';
import {everything} from '../models';

export function ClearHistory():Promise<void>;

export function CopyPathToClipboard(arg1:string):Promise<void>;

export function GetConfig():Promise<config.Config>;

export function GetHistory():Promise<Array<string>>;

export function GetSearchOptions():Promise<everything.SearchOptions>;

export function HideWindow():Promise<void>;

export function IsWindowVisible():Promise<boolean>;

export function OpenFile(arg1:string):Promise<void>;

export function OpenFolder(arg1:string):Promise<void>;

export function SaveConfig(arg1:config.Config):Promise<void>;

export function Search(arg1:string,arg2:everything.SearchOptions):Promise<Array<everything.SearchResult>>;

export function ShowWindow():Promise<void>;

export function ToggleWindow():Promise<void>;
